# constants for game settings
WIDTH = 800
HEIGHT = 600
TITLE = "Maze Hunters"
FPS = 60
TILESIZE = 32
GRIDWIDTH = round(WIDTH / TILESIZE * 2)
GRIDHEIGHT = int(HEIGHT / TILESIZE * 2)
FONT_NAME = "Bauhaus 93"

# constants for colors (R, G, B)
WHITE = (255, 255, 255)
GOLD = (255, 215, 0)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BROWN = (106, 55, 5)
CYAN = (0, 255, 255)

# constants for button settings
BUTTON_IMG = "button_img.png"
BUTTON_HOVER_IMG = "button_hover_img.png"
BUTTON_CLICK_IMG = "button_click_img.png"
BUTTON_WIDTH = int(1152/5)
BUTTON_HEIGHT = int(648/5)
BUTTON_FONT = "SugarpunchDEMO.OTF"
BUTTON_TEXT_SIZE = 25
BUTTON_TEXT_X_OFFSET = -47 * (BUTTON_WIDTH/int(1152/3))
BUTTON_TEXT_Y_OFFSET = -20 * (BUTTON_HEIGHT/int(648/3))
BUTTON_POS_OFFSET = 50
MAIN_MENU_BUTTONS = [["play", (WIDTH/2, HEIGHT/3 + BUTTON_POS_OFFSET)],
           ["settings", (WIDTH/2, HEIGHT/2 + BUTTON_POS_OFFSET)],
           ["help", (WIDTH/2, HEIGHT*(2/3) + BUTTON_POS_OFFSET)]]
PLAYER_UNIT_SELECTION_BUTTONS = [["play", (WIDTH/4, HEIGHT*(7/9))],
           ["sniper", (WIDTH*3/8, HEIGHT/2 - BUTTON_POS_OFFSET)],
           ["warhammer", (WIDTH*3/8, HEIGHT*(2/3) - BUTTON_POS_OFFSET)],
           ["sword", (WIDTH/4 - BUTTON_POS_OFFSET, HEIGHT/2 - BUTTON_POS_OFFSET)],
           ["RPG", (WIDTH/4 - BUTTON_POS_OFFSET, HEIGHT*(2/3) - BUTTON_POS_OFFSET)]]
COMPUTER_UNIT_SELECTION_BUTTONS = [["sniper", (WIDTH*(7/8) - BUTTON_POS_OFFSET, HEIGHT/2 - BUTTON_POS_OFFSET)],
           ["warhammer", (WIDTH*(7/8) - BUTTON_POS_OFFSET, HEIGHT*(2/3) - BUTTON_POS_OFFSET)],
           ["sword", (WIDTH*(6/8)- 2*BUTTON_POS_OFFSET, HEIGHT/2 - BUTTON_POS_OFFSET)],
           ["RPG", (WIDTH*(6/8) - 2*BUTTON_POS_OFFSET, HEIGHT*(2/3) - BUTTON_POS_OFFSET)]]
UNIT_SELECTION_BUTTON_SCALE = 4
CLOSE_BUTTON = ["close",WIDTH/2, HEIGHT*(7/9)]

# constants for menu background
MENU_BG_IMG = "menu_bg.png"
MENU_BG_WIDTH = 850
MENU_BG_HEIGHT = 600

# constants for the title
TITLE_IMG = "title_img.png"
TITLE_WIDTH = int(865/2)
TITLE_HEIGHT = int(136/2)

# constants for sliders
SLIDER_LENGTH = int(BUTTON_HEIGHT / 2)
BAR_WIDTH = 500
MIN_BAR = 104
SLIDER_X_OFFSET = -80
SLIDER_Y_OFFSET = -10
BAR_HEIGHT = SLIDER_LENGTH / 2
SLIDERS = [["WIDTH", (WIDTH/2 + SLIDER_X_OFFSET, HEIGHT/3 + SLIDER_Y_OFFSET)],
           ["HEIGHT", (WIDTH/2 + SLIDER_X_OFFSET, HEIGHT/2 + SLIDER_Y_OFFSET)],
           ["FPS", (WIDTH/2 + SLIDER_X_OFFSET, HEIGHT*(2/3) + SLIDER_Y_OFFSET)]]

# constants for unit settings
PLAYER_SPEED = 160
COMPUTER_SPEED = 160
ENEMY_COUNT = 2
BULLET_SPEED = 10
SNIPER_RATE = 250
SNIPER_DAMAGE = 10
RPG_RADIUS = 20
EXPLOSION_DAMAGE = 5
RPG_RATE = 100
SWORD_RATE = 250
SWORD_DAMAGE = 10
WARHAMMER_RATE = 150
WARHAMMER_DAMAGE = 15
SOLDIER_SPEED = 70

